### ISSUE TITLE
resize函数问题

### ISSUE THREAD

**Issue by toxmc** [hihozhou/php-opencv#43]
```
<?php
use CV\Size;
use function CV\{ imread, imshow, addWeighted, waitkey, resize};

$alpha = 0.5;
$beta = 0.0;
$dst = null;
$retLogo = null;

fwrite(STDOUT, "* Enter alpha [0-1]: ");
$input = trim(fgets(STDIN));

if( $input >= 0 && $input <= 1 ) {
    $alpha = $input;
}

$image = imread("hui.png");
$logo = imread("wm.png");

resize($logo, $retLogo, (new Size($image->rows,$image->cols)));

$beta = 1 - $alpha;
addWeighted($image, $alpha, $retLogo, $beta, 0.0, $dst);

imshow( "Linear Blend", $dst );
waitKey(0);
return 0;
```
照着C++代码翻译，用resize函数把图片放大成一样的尺寸结果报错
```
[xmc@mc Bwm ]$ php simple.php        
* Enter alpha [0-1]: 1
OpenCV(3.4.1) Error: Sizes of input arguments do not match (The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array') in arithm_op, file /tmp/opencv-20180529-55469-97fkx6/opencv-3.4.1/modules/core/src/arithm.cpp, line 659
PHP Fatal error:  Uncaught CV\Exception: OpenCV(3.4.1) /tmp/opencv-20180529-55469-97fkx6/opencv-3.4.1/modules/core/src/arithm.cpp:659: error: (-209) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function arithm_op
 in /Users/xmc/PhpstormProjects/test/opencv/Bwm/simple.php:30
Stack trace:
#0 /Users/xmc/PhpstormProjects/test/opencv/Bwm/simple.php(30): CV\addWeighted(Object(CV\Mat), '1', Object(CV\Mat), 0, 0, Object(CV\Mat))
#1 {main}
  thrown in /Users/xmc/PhpstormProjects/test/opencv/Bwm/simple.php on line 30

Fatal error: Uncaught CV\Exception: OpenCV(3.4.1) /tmp/opencv-20180529-55469-97fkx6/opencv-3.4.1/modules/core/src/arithm.cpp:659: error: (-209) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function arithm_op
 in /Users/xmc/PhpstormProjects/test/opencv/Bwm/simple.php:30
Stack trace:
#0 /Users/xmc/PhpstormProjects/test/opencv/Bwm/simple.php(30): CV\addWeighted(Object(CV\Mat), '1', Object(CV\Mat), 0, 0, Object(CV\Mat))
#1 {main}
  thrown in /Users/xmc/PhpstormProjects/test/opencv/Bwm/simple.php on line 30
[
```

**Comment by morozovsk** [comment]
put this code before "addWeighted()" for debug your problem:
```php
var_export($image);
var_export($retLogo);
var_export($image->channels());
var_export($retLogo->channels());
```

**Comment by morozovsk** [comment]
use https://github.com/hihozhou/php-opencv-ide-helper
new Size($width, int $height) != new Size($rows,$cols)

**Comment by toxmc** [comment]
```
var_dump($image->size());
var_dump($image);

result:
object(CV\Size)#3 (2) {
  ["width"]=>
  int(400)
  ["height"]=>
  int(626)
}
object(CV\Mat)#1 (4) {
  ["type":"CV\Mat":private]=>
  int(16)
  ["rows"]=>
  int(626)
  ["cols"]=>
  int(400)
  ["dims"]=>
  int(2)
}
```

$width = $image->cols, $height = $image->rows, So it works success！
